<?php
// N5IDE, Nemo5 InputDeck Editor
// NEMO5, The Nanoelectronics simulation package.
// Copyright (C) 2010 Purdue University
// Authors (in alphabetical order): Mejia, Daniel
//
// This package is a free software.
// It is distributed under the NEMO5 Non-Commercial License (NNCL).
// The license text is found in the subfolder 'license' in the top folder.
// To request an official license document please write to the following address:
// Purdue Research Foundation, 1281 Win Hentschel Blvd., West Lafayette, IN 47906, USA
	error_reporting(E_ALL);
	require_once( dirname ( dirname ( dirname ( dirname ( dirname( __FILE__ ) ) ) ) ) . DIRECTORY_SEPARATOR . "assets" . DIRECTORY_SEPARATOR . "php" . DIRECTORY_SEPARATOR . "constants.php");
	require_once( dirname ( dirname ( dirname ( dirname ( dirname( __FILE__ ) ) ) ) ) . DIRECTORY_SEPARATOR . "publications" .DIRECTORY_SEPARATOR . "com_pubmanager" . DIRECTORY_SEPARATOR . "source" . DIRECTORY_SEPARATOR . "config.inc.php" );
	require_once(SOURCE_PATH . DS . "InputDeck" . DS . "InputDeckParser.class.php");	
	$idp = new InputDeckParser();
	$idp->loadSession();
	header('Content-type: text/plain');
	header('Content-Disposition: attachment;filename="' . $idp->getName() . '"');
	header('Cache-Control: max-age=0');
	function print_node( $node, $level = "" ){
		$commands = array('_step', '_reinit', '_output', '_init', '_solve', 'solve');
		$private = array('_name', '_id', '_children', '_type', '_nested', '_comment', "_loop_count");		
		echo "\n" . $level . $node->_type . (($node->_type == "loop")? (" ( " . ($node->_loop_count*1) . " ) "):"") . "\n";
		echo $level . "{" . "\n";
		if ($node->_comment != ""){
			echo "  ".$level."/*";			
			echo "  ".$level . str_replace("\n", "\n    ".$level, $node->_comment);
			echo "\n  ".$level."*/\n";
		}
		foreach(get_object_vars($node) as $k => $v){
			if (in_array($k, $commands) || in_array($k, $private))
				;
			else
				echo "  ".$level . $k . " = " . $v . "\n";
		}
		foreach(get_object_vars($node) as $k => $v){
			if (in_array($k, $commands))
				echo "  ".$level . $k . " = " . $v . "\n";
		}
		if (isset($node->_children)){
			foreach($node->_children as $node2){
				print_node($node2, $level."  ");
			}
		}
		echo $level . "}" . "\n";
	}
	if ($idp->getType() == "input_deck"){
		if (is_array($idp->getTree())){	
			echo "/*\n";
			echo "  Input Deck Generated By NEMO5 InputDeckEditor\n";
			echo "  version 0.1\n";
			echo "  http://www.http://nanohub.org\n";
			if ($idp->getComment() != ""){
				echo "  \n\n";
				echo "  " . str_replace("\n\n", "  \n", $idp->getComment());
			}
			echo "*/\n";
			foreach( $idp->getTree() as $node ){
				print_node($node);			
			}			
		}
	} else {
		echo "Only Input_deck are supported to export";
	}
?>
